server:
  port : 8097
  
spring:
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop

  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/test;AUTO_SERVER=TRUE 
    username: sa
    password: sa
    
  sql:
    init:
      dataLocations: classPath:/movie-service.sql
    
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
